//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_details
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public string DOB { get; set; }
        public string Tele_No { get; set; }
        public string Age { get; set; }
        public string Minor_patient { get; set; }
        public string Address { get; set; }
        public string Country_code { get; set; }
        public string Country_Name { get; set; }
        public string Relationship_to_patient { get; set; }
        public string Guardian_Name { get; set; }
    }
}
